# site wide config:

name: SBAmin.com
url: https://git.sbamin.com/gitweb
paginate: 8
description: github:dyndna
intro: github:dyndna
logo: /images/site_logo.png
disqus_shortname:

# jekyll config:

permalink:   /:categories/:title/
gems:
  - jemoji
  - jekyll-sitemap

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Owner/author information
owner:
  name: Samir B. Amin
  avatar: http://www.gravatar.com/avatar/2d828f284f8b417a61e1930c9cceaaed.png
  email: 
  # Social networking links used in footer. Update and remove as you like.
  twitter: sbamin
  github: sbamin
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus: SamirAmin-Patel

# Analytics and webmaster tools stuff goes here
google_analytics: UA-307297-1
google_verify: -O-yqqP1MmP96ce2lYDmhbBJV5m1HC-gGnoKDcNYuHo
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
